# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-17 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mx_trade', '0002_auto_20181207_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_goods', to='mx_trade.OrderInfo', verbose_name='订单信息'),
        ),
    ]
