# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-17 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mx_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '首页分类广告',
                'verbose_name_plural': '首页分类广告',
            },
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='name',
            field=models.CharField(default='', help_text='分类名', max_length=30, verbose_name='分类名'),
        ),
        migrations.AddField(
            model_name='indexad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='mx_goods.GoodsCategory', verbose_name='商品所在类别'),
        ),
        migrations.AddField(
            model_name='indexad',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='mx_goods.Goods', verbose_name='商品'),
        ),
    ]
