"""
Django settings for mxshop1113 project.

Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#获取项目的根目录
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0,BASE_DIR)
#将apps和extra_apps join到项目根目录下 这样导包的时候可以直接导入apps以及extra_apps下面的文件
sys.path.insert(0,os.path.join(BASE_DIR,"apps"))
sys.path.insert(0,os.path.join(BASE_DIR,"extra_apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1nd(_gk#9=*4@^v=urnydd4rz3!xapy^blk)m#+oa9_d#jnnah'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
AUTH_USER_MODEL = 'mx_user.UserProfile'

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mx_user.apps.MxUserConfig',
    "mx_goods.apps.MxGoodsConfig",
    "mx_user_operation.apps.MxUserOperationConfig",
    "mx_trade.apps.MxTradeConfig",
    "xadmin",
    "crispy_forms",
    "DjangoUeditor",
    "rest_framework",
    "django_filters",
    "corsheaders",
    "rest_framework.authtoken",
    "social_django"
]
CORS_ORIGIN_ALLOW_ALL = True
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mxshop1113.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'mxshop1113.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "vue_shop1113",
        "USER":"root",
        "PASSWORD":"mysql",
        "HOST":"127.0.0.1",
        "PORT":"3306",
        #设置数据库引擎
         "OPTIONS": {"init_command": "SET default_storage_engine=INNODB;"}
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/



AUTHENTICATION_BACKENDS = (
    "mx_user.views.CustomBackend",
    "social_core.backends.weibo.WeiboOAuth2",
    "social_core.backends.weixin.WeixinOAuth2",
    "social_core.backends.qq.QQOAuth2",
    'django.contrib.auth.backends.ModelBackend',
)

USE_I18N = True

USE_L10N = True

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'     # 时区

USE_TZ = False      # 使用本地时间，而不是UTC时间


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        #用户和密码
        'rest_framework.authentication.BasicAuthentication',
        #用户状态
        'rest_framework.authentication.SessionAuthentication',
        # #drf提供的token
        # 'rest_framework.authentication.TokenAuthentication'
    ),
    # 'DEFAULT_THROTTLE_CLASSES': (
    #     #ip
    #     'rest_framework.throttling.AnonRateThrottle',
    #     #token
    #     'rest_framework.throttling.UserRateThrottle'
    # ),
    # #时间
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anon': '2/minute',
    #     'user': '3/minute'
    # }
}


import datetime
#jwt的全局设置
JWT_AUTH = {
    # 时间
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=7),
    #header的标题
    'JWT_AUTH_HEADER_PREFIX': 'JWT',
}

REGEX_MOBILE = "^1[358]\d{9}$|^147\d{8}$|^176\d{8}$"
API_KEY = "d47387abfe0eca2c0ac56591a5ae59e9"

#支付宝相关配置
private_key_path = os.path.join(BASE_DIR,"apps/mx_trade/keys/private_2048.txt")
ali_pub_key_path = os.path.join(BASE_DIR,"apps/mx_trade/keys/alipay_key_2048.txt")

#缓存过期时间
REST_FRAMEWORK_EXTENSIONS = {
    'DEFAULT_CACHE_RESPONSE_TIMEOUT': 3600
}


#redis缓存
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

#id和secret
SOCIAL_AUTH_WEIBO_KEY = '3025460285'
SOCIAL_AUTH_WEIBO_SECRET = '2a0ac99f02bd0bde544ff51d73652b92'

SOCIAL_AUTH_WEIXIN_KEY = 'foobar'
SOCIAL_AUTH_WEIXIN_SECRET = 'bazqux'

SOCIAL_AUTH_QQ_KEY = 'foobar'
SOCIAL_AUTH_QQ_SECRET = 'bazqux'

#登录成功后跳转的地址
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/index/'